# Generated by Django 5.2.8 on 2025-12-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='updated_manually',
            new_name='auto_marked',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
        migrations.CreateModel(
            name='FacultyTimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='09:00')),
                ('grace_minutes', models.IntegerField(default=15)),
                ('end_time', models.TimeField(default='17:00')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='face_app.faculty')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
    ]
